<PopupActionButton>:
    text: root.btn_text
    size_hint_x: None
    width: self.texture_size[0] + ((dp(50) if self.icon else dp(20)) if self.flat else (dp(44) if self.icon else dp(24)))
    padding: (0, 0) if self.flat else ((dp(32) if self.icon else dp(12)), 0)
    halign: 'left'
    valign: 'middle'
    text_size: None, self.height
    canvas.after:
        Color:
            rgba: self.color
        Rectangle:
            source: root.icon
            pos: self.x + dp(10), self.center_y - dp(10)
            size: (dp(20), dp(20)) if root.icon else (0, 0)
