
<ToolTipButton>:
    show_tooltips: app.show_tooltips
    tooltip_delay: app.tooltip_delay
    background_color: 0,0,0,0
    canvas.before:
        Color:
            rgba: (88/255,88/255,88/255,1) if self.state=='normal' else (50/255,164/255,206/255,1)
        RoundedRectangle:

            pos: self.pos
            size: self.size
            radius: [dp(self.tooltip_radius if self.tooltip_radius else 0),]

<ToolTipDropDown>:
    show_tooltips: app.show_tooltips
    tooltip_delay: app.tooltip_delay

<ToolTipTextInput>:
    show_tooltips: app.show_tooltips
    tooltip_delay: app.tooltip_delay
    on_focus: self.on_input_focus(self, self.focus)

<ToolTipSwitch>:
    show_tooltips: app.show_tooltips
    tooltip_delay: app.tooltip_delay

<Tooltip>:
    size_hint: None, None
    width: max(tooltip_label.texture_size[0] + 20, tooltip_image.width + 20)
    height: tooltip_label.texture_size[1] + tooltip_image.height + 20
    size: self.minimum_size
    orientation: 'vertical'
    padding: 10, 10
    spacing: 15
    canvas.before:
        Color:
            rgba: 0.1, 0.1, 0.1, 0.9
        Rectangle:
            size: self.size[0]+10,self.size[1]
            pos: self.pos
        Color:
            rgba: 0.8, 0.8, 0.8, 1  # Light grey border
        Line:
            width: 1.5
            rectangle: (self.pos[0],self.pos[1], self.size[0] + 10 ,self.size [1]) 

    BoxLayout:
        size_hint: None, None
        size: tooltip_image.size
        orientation: 'vertical'
        Image:
            id: tooltip_image
            size_hint: None, None
            fit_mode: 'scale-down'
            size: self.texture_size
            pos_hint: {"center_x": 0.5}

    ToolTipContentLabel:
        id: tooltip_label
        size_hint: None, None
        text_size: self.width, None
        size: self.texture_size
        halign: 'left'
        valign: 'top'

<ToolTipContentLabel>:
    id: tooltip_label
    text_size: self.width, None
    size_hint: None, None
    height: self.texture_size[1]
    halign: 'left'
    valign: 'top'
    show_tooltips: app.show_tooltips
    tooltip_delay: app.tooltip_delay

    canvas.before:
        Color:
            rgba: 0.2, 0.2, 0.2 , 0
        Rectangle:
            size: self.size
            pos: self.pos

<HelpButton>
    id: help_button
    orientation: 'vertical'
    halign: 'center'
    pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    size_hint: None, None
    height: self.parent.height
    width: self.parent.height * 2
    state_image: self.background_normal if self.state == 'normal' else self.background_down
    disabled_image: self.background_disabled_normal if self.state == 'normal' else self.background_disabled_down
    canvas:
        Color:
            rgba: 0, 1, 0, 1
        BorderImage:
            border: self.border
            pos: self.pos
            size: self.size
            source: self.disabled_image if self.disabled else self.state_image
    Image:
        id: image
        source: root.image_source
        fit_mode: 'scale-down'
        size_hint: 0.3,0.3
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}