#:import tr carveracontroller.__main__.tr

<SetXPopup>:
    size_hint: 0.5, 0.4
    pos_hint: {"right": 0.75, "top": 0.7}
    auto_dismiss: False
    txt_offset: txt_offset
    BoxLayout:
        padding: '15dp'
        orientation: 'vertical'
        Label:
            canvas.before:
                Color:
                    rgba: 45/255, 45/255, 45/255, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: caption
            size_hint_y: None
            height: '30dp'
            text: tr._('Set X Current Pos')
            halign: 'left'
            valign: 'middle'
        BoxLayout:
            padding: '15dp'
            orientation: 'vertical'
        BoxLayout:
            size_hint_y: None
            height: '30dp'
            Label:
                text: 'Value:'
                halign: "left"
                valign: "center"
                text_size: self.size
            TextInput:
                id: txt_offset
                hint_text: tr._('Enter X Pos')
                multiline: False
                text: '0.0'
                halign: "left"
                input_type: 'number'
                input_filter: 'float'
        BoxLayout:
            id: empty
        BoxLayout:
            spacing: '5dp'
            size_hint_y: None
            height: '40dp'
            Button:
                id: btn_cancel
                text: tr._('Cancel')
                on_release: root.dismiss()
            Button:
                id: btn_ok
                text: tr._('Ok')
                on_release: root.on_ok_pressed()

<SetYPopup>:
    size_hint: 0.5, 0.4
    pos_hint: {"right": 0.75, "top": 0.7}
    auto_dismiss: False
    txt_offset: txt_offset
    BoxLayout:
        padding: '15dp'
        orientation: 'vertical'
        Label:
            canvas.before:
                Color:
                    rgba: 45/255, 45/255, 45/255, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: caption
            size_hint_y: None
            height: '30dp'
            text: tr._('Set Y Current Pos')
            halign: 'left'
            valign: 'middle'
        BoxLayout:
            padding: '15dp'
            orientation: 'vertical'
        BoxLayout:
            size_hint_y: None
            height: '30dp'
            Label:
                text: 'Value:'
                halign: "left"
                valign: "center"
                text_size: self.size
            TextInput:
                id: txt_offset
                hint_text: tr._('Enter Y Pos')
                multiline: False
                text: '0.0'
                halign: "left"
                input_type: 'number'
                input_filter: 'float'
        BoxLayout:
            id: empty
        BoxLayout:
            spacing: '5dp'
            size_hint_y: None
            height: '40dp'
            Button:
                id: btn_cancel
                text: tr._('Cancel')
                on_release: root.dismiss()
            Button:
                id: btn_ok
                text: tr._('Ok')
                on_release: root.on_ok_pressed()

<SetZPopup>:
    size_hint: 0.5, 0.4
    pos_hint: {"right": 0.75, "top": 0.7}
    auto_dismiss: False
    txt_offset: txt_offset
    BoxLayout:
        padding: '15dp'
        orientation: 'vertical'
        Label:
            canvas.before:
                Color:
                    rgba: 45/255, 45/255, 45/255, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: caption
            size_hint_y: None
            height: '30dp'
            text: tr._('Set Z Current Pos')
            halign: 'left'
            valign: 'middle'
        BoxLayout:
            padding: '15dp'
            orientation: 'vertical'
        BoxLayout:
            size_hint_y: None
            height: '30dp'
            Label:
                text: 'Value:'
                halign: "left"
                valign: "center"
                text_size: self.size
            TextInput:
                id: txt_offset
                hint_text: tr._('Enter Z Pos')
                multiline: False
                text: '0.0'
                halign: "left"
                input_type: 'number'
                input_filter: 'float'
        BoxLayout:
            id: empty
        BoxLayout:
            spacing: '5dp'
            size_hint_y: None
            height: '40dp'
            Button:
                id: btn_cancel
                text: tr._('Cancel')
                on_release: root.dismiss()
            Button:
                id: btn_ok
                text: tr._('Ok')
                on_release: root.on_ok_pressed()

<SetAPopup>:
    size_hint: 0.5, 0.4
    pos_hint: {"right": 0.75, "top": 0.7}
    auto_dismiss: False
    txt_offset: txt_offset
    BoxLayout:
        padding: '15dp'
        orientation: 'vertical'
        Label:
            canvas.before:
                Color:
                    rgba: 45/255, 45/255, 45/255, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: caption
            size_hint_y: None
            height: '30dp'
            text: tr._('Set A Current Pos')
            halign: 'left'
            valign: 'middle'
        BoxLayout:
            padding: '15dp'
            orientation: 'vertical'
        BoxLayout:
            size_hint_y: None
            height: '30dp'
            Label:
                text: 'Value:'
                halign: "left"
                valign: "center"
                text_size: self.size
            TextInput:
                id: txt_offset
                hint_text: tr._('Enter A Pos')
                multiline: False
                text: '0.0'
                halign: "left"
                input_type: 'number'
                input_filter: 'float'
        BoxLayout:
            id: empty
        BoxLayout:
            spacing: '5dp'
            size_hint_y: None
            height: '40dp'
            Button:
                id: btn_cancel
                text: tr._('Cancel')
                on_release: root.dismiss()
            Button:
                id: btn_ok
                text: tr._('Ok')
                on_release: root.on_ok_pressed()

<SetToolPopup>:
    size_hint: 0.5, 0.4
    pos_hint: {"right": 0.75, "top": 0.7}
    auto_dismiss: False
    txt_offset: txt_offset
    BoxLayout:
        padding: '15dp'
        orientation: 'vertical'
        Label:
            canvas.before:
                Color:
                    rgba: 45/255, 45/255, 45/255, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: caption
            size_hint_y: None
            height: '30dp'
            text: tr._('Set Current Tool Number')
            halign: 'left'
            valign: 'middle'
        BoxLayout:
            padding: '15dp'
            orientation: 'vertical'
        BoxLayout:
            size_hint_y: None
            height: '30dp'
            Label:
                text: 'Value:'
                halign: "left"
                valign: "center"
                text_size: self.size
            TextInput:
                id: txt_offset
                hint_text: tr._('Enter New Tool Number')
                multiline: False
                text: '0'
                halign: "left"
                input_type: 'number'
                input_filter: 'int'
        BoxLayout:
            id: empty
        BoxLayout:
            spacing: '5dp'
            size_hint_y: None
            height: '40dp'
            Button:
                id: btn_cancel
                text: tr._('Cancel')
                on_release: root.dismiss()
            Button:
                id: btn_ok
                text: tr._('Ok')
                on_release: root.on_ok_pressed()

<ChangeToolPopup>:
    size_hint: 0.5, 0.4
    pos_hint: {"right": 0.75, "top": 0.7}
    auto_dismiss: False
    txt_offset: txt_offset
    BoxLayout:
        padding: '15dp'
        orientation: 'vertical'
        Label:
            canvas.before:
                Color:
                    rgba: 45/255, 45/255, 45/255, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: caption
            size_hint_y: None
            height: '30dp'
            text: tr._('Change Current Tool')
            halign: 'left'
            valign: 'middle'
        BoxLayout:
            padding: '15dp'
            orientation: 'vertical'
        BoxLayout:
            size_hint_y: None
            height: '30dp'
            Label:
                text: 'Value:'
                halign: "left"
                valign: "center"
                text_size: self.size
            TextInput:
                id: txt_offset
                hint_text: tr._('New Tool Number')
                multiline: False
                text: '0'
                halign: "left"
                input_type: 'number'
                input_filter: 'int'
        BoxLayout:
            id: empty
        BoxLayout:
            spacing: '5dp'
            size_hint_y: None
            height: '40dp'
            Button:
                id: btn_cancel
                text: tr._('Cancel')
                on_release: root.dismiss()
            Button:
                id: btn_ok
                text: tr._('Ok')
                on_release: root.on_ok_pressed()

<MoveAPopup>:
    size_hint: 0.5, 0.4
    pos_hint: {"right": 0.75, "top": 0.7}
    auto_dismiss: False
    txt_offset: txt_offset
    BoxLayout:
        padding: '15dp'
        orientation: 'vertical'
        Label:
            canvas.before:
                Color:
                    rgba: 45/255, 45/255, 45/255, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            id: caption
            size_hint_y: None
            height: '30dp'
            text: tr._('Rapidly move the A to')
            halign: 'left'
            valign: 'middle'
        BoxLayout:
            padding: '15dp'
            orientation: 'vertical'
        BoxLayout:
            size_hint_y: None
            height: '30dp'
            Label:
                text: 'Value:'
                halign: "left"
                valign: "center"
                text_size: self.size
            TextInput:
                id: txt_offset
                hint_text: tr._('Enter A Pos')
                multiline: False
                text: '0.0'
                halign: "left"
                input_type: 'number'
                input_filter: 'float'
        BoxLayout:
            id: empty
        BoxLayout:
            spacing: '5dp'
            size_hint_y: None
            height: '40dp'
            Button:
                id: btn_cancel
                text: tr._('Cancel')
                on_release: root.dismiss()
            Button:
                id: btn_ok
                text: tr._('Ok')
                on_release: root.on_ok_pressed()
